### ISSUE TITLE
encounter a debug when running mistral model

### ISSUE THREAD

**Issue by qinglongheu** [WhereIsAI/BiLLM#11]
Traceback (most recent call last):
  File "/data/qinglong/entity_extract/billm_ner.py", line 158, in <module>
    trainer.train()
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/transformers/trainer.py", line 3238, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/transformers/trainer.py", line 3264, in compute_loss
    outputs = model(**inputs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/peft/peft_model.py", line 1926, in forward
    return self.base_model(
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 179, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/billm/modeling_mistral.py", line 439, in forward
    outputs = self.model(
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinglong/.conda/envs/billm/lib/python3.9/site-packages/billm/modeling_mistral.py", line 141, in forward
    bi_attention_mask = torch.zeros_like(attention_mask)
TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not NoneType

**Comment by SeanLee97** [comment]
could you provide your transformers version?

**Comment by SeanLee97** [comment]
@qinglongheu you can try this branch:

```
python -m pip install git+https://github.com/WhereIsAI/BiLLM.git@bugfix/bi_attention_mask
```

**Comment by qinglongheu** [comment]
> could you provide your transformers version?

my transformers is 4.41.1

**Comment by qinglongheu** [comment]
> could you provide your transformers version?

looks like that modeling_mistral.py -141_prepare_4d_causal_attention_mask_for_sdpa led to attention_mask is None, hope you can check this.thank you

**Comment by SeanLee97** [comment]
@qinglongheu  you can reinstall billm via:

```bash
python -m pip install git+https://github.com/WhereIsAI/BiLLM.git@bugfix/bi_attention_mask
```
